# Generated by Django 3.1.4 on 2020-12-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default='song', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default='Unknow', on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
