# Generated by Django 3.1.4 on 2020-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20201208_2101'),
        ('music', '0002_auto_20201208_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicplaylist',
            name='profile',
            field=models.ManyToManyField(blank=True, to='authorization.Profile'),
        ),
        migrations.AlterField(
            model_name='publicplaylist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.Song'),
        ),
    ]
