# Generated by Django 3.1.4 on 2020-12-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_artists',
            field=models.ManyToManyField(blank=True, null=True, to='music.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_genres',
            field=models.ManyToManyField(blank=True, null=True, to='music.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='songs_liked',
            field=models.ManyToManyField(blank=True, null=True, to='music.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
