# Generated by Django 3.1.4 on 2020-12-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20201216_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
